def image //explicit saying to use docker image

pipeline {
    agent any
    stages {
        stage('Build') {                 
            steps {
                script {
                    image = docker.build("sixeyed/pi:psod-pipelines", "--pull -f m4/Dockerfile m4")
                    //docker build details
                }                
            }
        }   
        stage('Smoke Test') {
            steps {
                script {
                    container = image.run() //run the image to perform sometest
                    container.stop() 
              }
            }
        }
        stage('Push') {                 
            steps { 
                script {
                    withDockerRegistry([credentialsId: "docker-hub", url: "" ]) {        
                        image.push() //final stage, log in docker-hub and push the image
                    }     
                }
            }
        }
    }
}