pipeline {
    agent any
    environment { //variable set 
        RELEASE='20.04'
    }
    stages {
        stage('Build') { //many steps in this stage
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..." // string interpolation
            }
        }
        stage('Test') {
            steps {
                echo "Testing. I can see release ${RELEASE}, but not log level ${LOG_LEVEL}" // string interpolation
            }
        }
    }
}