library identifier: 'jenkins-pipeline-demo-library@master', //import shared libraries
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/sixeyed/jenkins-pipeline-demo-library.git'])

simplePipeline() //using simplePipeline where has agent and verify steps